[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1fa613934583dc1c4bd625a3bb6d46d165c9486"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "8040ec4f50d1a2c66d2c5c61b3c2b20453e7ac8b4df80674d0bf684b087733f9"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9eb3ac72ec5066ce4b7348c0b59d79abefc8b40e"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1f67c9a7fb82b10491004f3629ea7b8c5fbc21b15de93e0f71836307b603250a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e012ec1b025dc46742a49b87858b1bf0d542ab23"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d7ada3f885a623b7b3a4ebd7e28ef1c4be07b95751e06889ccc705cd0bd44ab3"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0d409917ef8a25d9306000567127210caf57d48"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1f7319c1b735deb275a43bc8053ece7da9913a1cf1998f5626a30c51e1ccaa7e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "697d15a6188f5c66cce3cceb0ae759731556713c"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f775f7f07d3082b724604dbc8c60e6d0393df52bc5405bc47de98e69b7761b14"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b32668c2a95327284e456b80ccc3c4acda684f8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a86df78e45be30466f115f8a92de4bb19f0a958184333224e1b8697330bddc2b"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "352e502448d8d75fb85a904c232d42a6a96f7bbe"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "ed4fec072df8a8a2e18d3c1b55682eef5f82acf59fbb62aca00039d95cc84a8c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f8e8e0373c508f0f247d937269f58d7fd0d6b1e"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "43dd9376e091067819d8cd2e48201d4eb88b7e75d15e465a48b4bc9a2123106a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv6l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db606ec8039c37ef063fc9d1efd836c90e768ddd"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "bfb379cbd585c4ec7262bb3a9196596377bf3adbd0aee1af158ec219d6a528d4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv6l-linux-gnueabihf-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8641886f6802947e0179acfd9e8d982fad3d7263"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "5560656fad594c34d86d5d1d03df7939239bbd85d51cec87b0d1ceaec6155139"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a5a7bec1be68b9b7e6d6422e0c484178594b26e"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "fcf9dcf40dd554c61b24c07eba37840562e4bb7571c8b867d011f55223e2468e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv6l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0439e9ed6c112f3908ba40f6ef7c083e6b68cac"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "3c14c86a1c773862d7748bb99de5f22e8aaa41b81df658432105f080b2680fab"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv6l-linux-gnueabihf-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d04972b357e3af9b5d7b523292409ec32ba1812"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "ed412554edbbb0625bea374418c4dc04bd1d2c7f38b776c8b2da84d636397086"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "837c83178df1c6a326ec416cfca4f8ed0b818fe1"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "153d2e08fea7b2cfb7dedce168ce869a3f5d117822f2771a4b6188f02379408c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee4fc358c49989e293eafa5a9062a015543a3c58"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f016b09ad8469e16d2eb9590e413be3fa67d71589ca4c46b163f938dd20ad772"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b317f0c8dba5b4d425a3b370401fe4cbc7d38973"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f63ddfe7bbac047ecac59139ad0691cc39427ca8b6fa30c5826dc2e08c48f9ac"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "696ad9742a541e55f3196e9e5bbdad271a4c354c"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "4d74a4cb3c12312427e4261103bf20da492bf022387e62d48266de7ad91d4ef5"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0bcf166334e0eb5f46fc42510fe3c1079e2b3eb"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "27dd40ebf745f5468ffe3215cc96bc977953342d9d4f6152baa0548766bbc52c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cc1c4a0d65013118ba93701c26a579b2786198a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c29eedac523780ed985275a972124511939598be74fcf8c93cb6e1a778472035"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.i686-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fdf07bc8d7e82b4eb65ecb2defb01229059bc0b"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "30465e8cb79c3c4b120b785a996e7ebd62df137fb7dabef34a53931949b81034"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.i686-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ee252d4b18e7bb6e1a1f48f7160f0e1f4afbec4"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "8106107c62095b9b916503b77204f1764b641a9be3c991be95b41c8ac1477160"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbed4749b0d50b4efc10855bbfa0f60269336f5f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "14960b5ca14384397b61603ed09d13e8325a2f0ffcc082a616f399668433733c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.i686-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ba934cec2517ee4f07b046c6fddd0d2f4124ea5"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c342cfcc3fa9e2e3d79dbaa49f61b891fda5bfc2c2cac1597adff8b305a94eff"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.i686-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "823a7b55aa72325734c0fde8592d0ce01925f86f"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "93b79d96c43a3334df1dbb6285dd3150d03ccdbe2d54b1d15d3fef266a64c61f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb71da97b45981b7ba949500f311895a15992d21"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "274223c548095b7c7139f97c19051031c13223de0dc354b694217e6af0da03a3"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcde9cecbfccd8f996d2d82c680fa9472a4d4719"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "646aa3c1b740f268a903902628a87c72479dbdc6bce87aac72a8b569250368c0"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5320ce817caefed2e06ebc1091d7475cb554accf"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "8250b14cb27bdebfa58d3da6ff86b538dac8b6820ac2a1b9aa12cb39540487fd"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43c8ba1c3de87f5dd65ef8a3174b462e203f6604"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "aa17c8b21372bc793f3349d85536877ffc6788e1bd36ada57ec1de505a3a3c23"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "118a2ff08525500373955efbd1bd374f56f4fb94"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "5f2e4cce26c550abe146cb3ff2ff68735443ef49893480afa47379951be11511"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1723266cd4cbc91981c9bfb9f4dcc3e203b437c2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "3b88af07d7824176b9bc897ea4045e00ba847ca4e2c03ceabe19be1c89485878"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5dd94d2f65aa8cbc392ca3ba2687acd294c03767"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "551b15ddbc4d0ba9300d51a5f98e5743f8f7bd4da35e414737405a32375f7e14"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e868e2e25e701160d2a50f56147e3fa4f6e4ffff"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "80251d284639ddc71993c565fcd765b9f4acd73d493e7408959b8b893539d827"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "457a1318e2330a1f521f8d05b306649d440a4bf1"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a504755f2ac87219007c8c0a5b3cd6b84e0ca5a7363fef85d739eb646dcd999c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac0badbfb7071d3b4b47d7e0d433f234a145e990"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "fdeb1dc2f9a365ab5cf8239ec78f36f6ad5ce835414f4267e58140afbc7ce69f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5d79ffa2b6e8aaa36b18b39920f93eb59ef1ac2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d2b0d8cd3485aa814839a6e47b107f4dd3a59f9ad51c915ac24770dd77e0f8e8"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3267051bd2a78989c09e53152260eff51ad2036"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "992bea86d308c69e15118d58b658b8825f7b07d9c8eac6bfc3d13a4e01a3481f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.1+0/casacorecxx.v0.1.1.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
