[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "aad67b492195bf48accd9da04c790c9e917c4d5d"
julia_version = "1.10.0"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "63b5bcf89766f26a21038c67eadc884de44426e47856e3ac07944f60dfa9b8bc"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "6d70168e27becbba54c8585ef98a1a311d8fdd3a"
julia_version = "1.11.1"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "448aeef6ecf882883e52a0e17ec725f14e12da8a7b60e915b1bd8f50454534c8"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "28c13b7d9627a7abc6710475e3f84d556b9e55b5"
julia_version = "1.12.0"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "84e135554694929153b1a5d8dcd6ef6ff218232f5d30e019f7dba45548a81965"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "dcba2f38e673edc51bcc80cf5e2ca7b9950fe72d"
julia_version = "1.13.0"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "f22c10636749dd3313a19704ccee3c20d4673e8581b35ca97e88a71c9f370a8f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99c0d7c0ceb3c40f117a2a8830f11c02c4c6e9b2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1b2f53fdcaab606887e1af43a236003817d4d641df97162dba8824c68e7725e6"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05ce8017ec58eebc0d5a49c436a2f953c3960947"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "20e4afdb8b741bde556b2f183c5e60dcf9a8787fd596aaa390a879d028fbd86f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac0635d28925205da164666d7dfeb80ca64988c2"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9d07e90c412ffb87d4421583c2b22333a309dae5fea3a3d523bb554195e7c024"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "488c8ba096456bbc797e396a6ab82a429791f10b"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9567e0f90206aef90ae58a328a5e25018b29cc12c67327c386647a054673468e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5191817c6e49600c15a05b1421ca677844b0366"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "615826f536698c36daef024fa0316893fa8cc5686a35eff1de82e316715329de"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e926abb276499db3bae11095770dc48c12035f0"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b0cf9602af0a2c31f94da2e572a15fc417ee8cf6364ab0765bbc7bab47e5268b"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.i686-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b9c175df6a0c2fd9dc27d753767847d4ac11b10"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "8ebe79a9e303bf6657e74c2bd750a79f6cf1dd3d1ac94251b233bb5823b0fc72"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4118182dc3c2e0977fa02b53ea050abd6531e1dc"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0c78757a1904e06eb4eb05f181d18e6eaf4d1198e5f6d461ea6203c48c64ef7e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.i686-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c842a6bca09a7135ba4f2717711b1d1fc531ac70"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a7c7ac8208636f628d7614d7cbc205bc9bac4766b1ec02bc4d22d0dcc369cb40"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0baefb74a48b629c47c2e82470fb68a44a83ce7f"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "cb163f201a9b8043c3ca5470ec844a2a8e40a5f69c9a65eeb5e2cf8c1ae41960"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e47fdf372930dd7c240cf638e4c63c784cebad6"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a91d7c8542c8dc482dae3adc2036ef0a887c7256fa765d0ee891a11a8a147525"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab090403851171bd74238c1a7d5804b102eb59aa"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b292465c903ce92847163c7d446be13c12a63b53815a89cc0b508723f2687bdd"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "b29e9350a42091399de196c9b03fe35a08e36d78"
julia_version = "1.10.0"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "4349a5788edd38e3f3ddb92b5254e2b07cfb3445a754a8ac9c35c9bb39f1f4be"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "ec1eac95609db1c2b6c64f6606143cb99d7f287e"
julia_version = "1.11.1"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "6e7cb879e55f6750e886bec6f9532c8077d216ec8b65127df27ba33152975a9f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "0e479f300246c0cbb105add12b268a42b2e391ef"
julia_version = "1.12.0"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "888fd2d2818d7b1c27106f3e511ac4b1da7185276ccc7c823d542da688cc482b"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "c69ca7cf1296451ae8d9640c14beacc5340112cd"
julia_version = "1.13.0"
os = "macos"

    [[casacorecxx.download]]
    sha256 = "61e1c489c5f802ecc3d37de35ef36b92396b90c47c0e260d666032edde9fccb8"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "694b27740d435f03a293ca913fce1b6ca98b2ba2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d2aa1f14f78c003d1333ccb096f1f262043243777d2f3a10763ff5d390906a05"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d208b4d59ea25700e2f0c693568dd9b053d2a16a"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b066fb1b0cc7e50c6a2af80242a46d168ca5f4837e00f0f422f17b1327aa962b"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e9b80437ce1585dcfbae96a6b22932f142cb16"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "db75a761a39b4bfd9608f379f3bb2e4fa5bf879d7f226de0291ad1c807203bd9"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43806002727608f4d5b873f85ff6e9d639ebe222"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "ea2dfa01c0d16875ed43efcd33ed88279151b0a227c380c7cf86f8a40efc9bd2"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.4.0+0/casacorecxx.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
