[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc8cbdc54ddd18c1d9927abb5aae1806772d0965"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "783a3a8a737b8951a66b12f7b228d1be0bdd41e805d48abebe7c0bd95a968e01"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c61a38da07aeb51fd9032b98d590656ffa5a2b3"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "df71243db571408a22738d243d5db8883666ebaf5b3b9dad2e0bf6abbc46a461"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "146c622d40e9b15a6a0d2f3e5c30793a4cdac48b"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "4c8164586758a793de62b7b0abd00e2e209fd00345d4ce2a96160d6cd5819c07"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa03e099e4c02058a495b9413218282227d7025a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "233e037850213d4eb901d74ea1079f2690efa425436225dadef49c11888e323d"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05c83f7292ccdc025f2e21a55ee7ed7c569b03c6"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "123446fe39877d6f90eb288ab0bc63df035df8698d81aa5867d8017293cc235e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b90e48b52eabbf8f272cbffe6f247f3c0f54eec"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b9a32e3130af6c7570f02a1c66c7d71f0358d30223a8db7650f83154dc029a9c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd15745dacc4188714ffc63bbf4976330fb3d84d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "7f2ec01ce56b2ae077c79c50ee9d85219099529d67347f34138e9602c1c0df6c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b53d4fc3f684af458262f4ad3039b4379e55560"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "088d2e5e18a0fab5b1386a0c43b288ed4255fe1c2711bd0a87f4fef99b04dbb5"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv6l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "371ece39c9588ecbe068ac752a50717929420464"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "618d0b4e1f2d3d8aecee3dd544cf5dbf8971e4e371dc5f2a1ada35958b0dcaa5"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv6l-linux-gnueabihf-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cd0b835cbe34eee9c0529a7f2c9c9181f783a1a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "66dc447260317236f2fc2aa2582b3d08bc99e3572cb1335cfc07f59a83210093"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2651b647206a07ea6b370df6e7815ee29d733a17"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "47fe62ef6881b47143f80d39d12a64c4be4920fbece247fc149126e76cbba0d5"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv6l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e627e32496127b64ab9e046a3d4ff8a3ed35f4aa"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d1d371ca2a35b6bb21182efc6e90ad105d4557b12170eedc6e9ff0ac89da8ffd"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv6l-linux-gnueabihf-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1b306ab8cfc52c21008633d7ef9b69d2c03b8cc"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "364a0b5d8e50ce21a0d6c51e51db3a83a1a031a75d4e8ed4ad108dfe85681eb1"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "490944540ab401f0eeb875d109df30c393eb725f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "3ca80a16924887fd22509ac9c0e4b1424283fbab2729ac213f7aab64a5ee04e3"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv7l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c4600177b3a269153ff075af8df04ec551681e0"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1fe0d5512a95ea28ce71950edc038d4c10f0cf0595d1134b8acbba131d7cb677"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv7l-linux-gnueabihf-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e3421521ec094af5a15334c312cf589ab0f74fb"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "ae9a01d379f90a2980c26d470626139874f7168cebc5cabfc374d823ed9f8bea"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32c09114c5494186190bbf9bcceea8f8259957b4"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "6dade57fc029ca496215120d0aea8cb174e1bedd118ccb9de1897758233a9f3d"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv7l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e870815964e9c994789dc9ff0bf1b5c219f0413c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "eec0d2cbb20948d8da34dc23bb2e58e1cfab20d46239a194cb85a92a3688aa14"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.armv7l-linux-gnueabihf-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09ec600fb5ce62acbb83f38bfee36f1cb9e42bc8"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "78283c92f64665791a51826947bd3e25b476ffe308928a94ecbb47ece565637c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.i686-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02614fa2519fa429cf1079e626aa9abe313a4ed4"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "fd59c87f0697c7cab23c07e7393321b7cb0f83bff48cc90d6bb3b636c49f6204"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.i686-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d1b94d92de9542895ab8076565f77992cf91be6"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b4e3e65fdaf0e8beca548c2a9a39a1e99ca7058bea43a1be5e6033372230cd85"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85ea2bcbd6a65c96efc3dc1b7f7e5359112c8a1b"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f259d1a6e25e8e046721debd7a396f5c0ebccaf58fd16b670fa682e6d6e7ae0f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.i686-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd4423cefceea8a267a85d57d665ccca7db30091"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "69bcc4ead92693bb713bc44406f68203510c4904f32e8e4a9bc93586b477c27e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.i686-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5d1cce5d69cdc9a24158d9f73839bb9e29e326"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0f8d8947deb38703ae799247e22f1778f18c75d615a53e886ae72e11a8f67184"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a23e12091013fc240213bb5ca539514b264277d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "97098ff3d0b731fea83f364e698feeccb6a2e4f3cca812fe365ca27cec77b61f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c11edf12590921fcb28e7cb624d40037e5eb38c0"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b969c922e5140b1380769812f67e87c554c1e2061b8d201a089b058100031388"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d5c6157c71e6162469d6ba113183351a970ffe2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "8c353c6ad62ab7af629ffe87930fe17b9ffe809e4205e1746a7475190d703237"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7dd3e3f563eac3ca6a648e7aa1d25683d198a10"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0209a348e9c573d1989667bab2dbdcd1acf9d557d9dea2d59e9fda1ed0332cd2"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "360c609e5e8d91c8bb0a22886f7212fe143369e1"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9736424b5427bd94d7bf73a50aabe5a54c7c869374e264c86e93a6974a9a1cae"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50ba766b5eb290a08ed681888139276ee57879d5"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "5e7563022d5df3e3d4ae5ff042b85a5fa5093a5860c1894c9d70362f26aea621"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d549e5610a3e3ef18a29296184a120ccd65454c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f2372178d5d504f3fe12cccb53be994a515471d873bb4a16e1dbf553f99857c1"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79e1f5bf00d0f55d1a86deadc111ff7c1512846f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "897156106e89975ea6e1fcd1f4ad7d43f00d2b30eaef1bcf53f81a0d0055f39f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a2ae4ba21b6e11408bbcc161942de0627ab7a57"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "e57e2a5c0898f83d40d7403f7e84bcd3188156ef97127961806af071575678f8"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cea3ac2c67e3f5bfd75adfc88613b5a412703944"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "ade3dc13847853a1804a39e7eeabf752b0714fef4de1724f1804b840553e7e29"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71d301f56a87b6fa4c78d3a2469c7ff7ea273158"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "07b93ac7aed6871325faebee560bb1561e5778748eb22d1463766c2c341c1c29"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0273c9e58fbf93a34bc2450cd79430b66f7877f"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9d7b84a8416162598f4452d6d73a9705bf3adc4517eacb7e114f9a5194cc3e3f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.1.2+0/casacorecxx.v0.1.2.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
