[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "a318242be3346b57c2c3fe50fdab9b525a9d3c4d"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "3d9f306f239c41a42798258967e3c18cf512449d5bb8489be569f241d38acf99"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "3404c65ff75ce1b136ea10da556aebd168f433e9"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "2e2a708a6ade5d7ec6ac2e0bd39459b780aaa7080bfdcb5c94d1f4a975a28f28"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "a8a7350c93e780a592d938ef1500f8690855566f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "49e6ec33fd9b6315cea4c135476252e8423866a71f58e4a21f02933a4202f10a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
git-tree-sha1 = "a318242be3346b57c2c3fe50fdab9b525a9d3c4d"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "3d9f306f239c41a42798258967e3c18cf512449d5bb8489be569f241d38acf99"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20625e4a9cebe8010e2fcceab1ea8c8652c9864b"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f774d0279bbe342f65b7bbed57c8556374ff83bf74edb016a0ddca550477aea0"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv6l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80289b7ec83240a0ff46dc7d048b5e3eb2bd24a6"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "3e1160db3ce39830a8435ad171e570867759fe9118f1fa820c382cdd74e81dff"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv6l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "789856d3d38ef93f5827f0b334d3cf82e07b3ff7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b9cd054da526343e40ca62ff4f7b6b8d1a916017d2816720bc4aac817385eb9a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv7l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44b84009cb16be8170e38fc93b719175f6edb4e2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f137aee225066cb958993f4c79760c2891be35027fdb31d00fbfa253115b46a4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv7l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
git-tree-sha1 = "367bb6b73b039a97799099994d0382dc2ca0b7db"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c152b4a84048df6a6dab7a6fb733b7c4dfe9efe44e7df309cfe1b366cbe30231"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "i686"
git-tree-sha1 = "0ab921ce3da7f4c685492bd46745e0de3014c18a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "f2a964a366a2573bce9145c2a9a0c9a9e924ff9ad56171377586ec4ab186034c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
git-tree-sha1 = "e8eb6a47a1483ad371caed2ad6a4da1ba40f173d"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "4c1276412eb220e730a8a35fc8e6fa23e887ed6fab6f7f6741883a07d990b5f7"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
git-tree-sha1 = "367bb6b73b039a97799099994d0382dc2ca0b7db"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c152b4a84048df6a6dab7a6fb733b7c4dfe9efe44e7df309cfe1b366cbe30231"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
git-tree-sha1 = "5cab63de24bf75a742faf13e47f73967e230f190"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "11845182beff8a1521f99866d437f86b4990a72225e4c6e70a031e8547da401b"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
git-tree-sha1 = "f9573b10d71fad1a4b941dc21061f1d7ec0cb4c7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "678577b24e41cdc1aae777ca2c8b2718cc96a78a9796837030ec2b7e6997a025"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
git-tree-sha1 = "c02d6822c8ecb4ebc071ba27c5795f481613dd15"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "62cf028f9af6636b8d3a6342259d96bd071675dff9d86e44c575dbfee7ce8491"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
git-tree-sha1 = "5cab63de24bf75a742faf13e47f73967e230f190"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "11845182beff8a1521f99866d437f86b4990a72225e4c6e70a031e8547da401b"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "91a10a6cd0f4b525c7bbae314048dce212acfd36"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "898d204e413f7008ad056a18074e884deafcd1dfb53c405b9af5d343c8d0488d"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "606cffa22d4ac44a31f4af72202c7af555417b44"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "23870ccb226eabc65cbff5f60776fc7c551a3ae93dd32268c8e1599d4c806343"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "f321eec0b5355789a2c9a49a6b0ca72b7f7ecf19"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "eb9f11aee2b7fb0a80c152fcb938f78106c20966b910ec84c5347b943b926dc4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
git-tree-sha1 = "91a10a6cd0f4b525c7bbae314048dce212acfd36"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "898d204e413f7008ad056a18074e884deafcd1dfb53c405b9af5d343c8d0488d"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
