[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b29d6ee3f6c9e16e4aa65a363982df52373421f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1dc5f8d2ffd623179f2a3db025ba0939880432d2c5b2723c5c9519ec800b7b20"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6278330dabd5b078abe67f1bd4651a6ab053fa7f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9290cd973a95a5c1bbea2b31bb74484ff5e0ff02788f839e368f7de5c6535054"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a98132fb641b159e89291c72cc748c9ec8103448"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "acdc3407e2d17738d5bf2259383822e3f2074ad8ba4db71d4f4644e587d80ea1"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f7fc128e8e8e5d10e049568b68b962a04880f78"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9cc4835df764a6dfa99a09b118c77efc3a6c13d874d9683193521f367b66fa78"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd224ef08757139eb513be27f3a5e3c884a127da"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "38b507bf2dd29efd445488c9b7a9fad76b65a2a20b6668ae872dff7ecc976ac4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c29c1b3bf7ba73e5124e6435fc7c6b4a4ee6c22c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "72ba92ae36fee0ea6ae77c2832ee10c8c5cb50e280822841ae15bd2796975031"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2411b84df21306297d5e1a69f7298a40c23dc333"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "cab42ac8569adcb3a7176e78e948570e11c6e4c6ec7e230bb43f4b49a241dcfc"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09370e7eff317c714ccc024b5b03c52ea30fdc2d"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "7c3d7aff841d4a9c7876dc5b66a40a33b53593cdbf359d3fe28cfc3c172711f1"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv6l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39235c319460681ded986260107ef9a46176dba3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "18143a7893748b7017a0b14426c0d0281106cc830052c9ea322b086bff6fe715"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf6d6bbbe1aafdc6f015276db4dc40cf42a30d7a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a6a2c95fdba70cf545ec464da01dd99d0468a0c1e52eb3cbdfb4e908213268e4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv6l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "556e7becc9043d16258a7e1ab4cfced47d29ec1c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "24ed9cc667cfa735be2f6df54cac5ba4747b3a9fad60d8b5be906333e348579f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3d29751e3b6e6811c9e5d200a03cfdf6d605827"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "7f34ed57908308f78adf861bd1d1e1197a8bd1dab4088b30136b882c68d42938"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv7l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87bea8058edcc3817f01aced10ecd0863593d298"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "5ef01298e9a4db2141b7f6137e59e183c0dbea27c1921cf80f96832af154bdc6"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4a11edcb2299e10fad0972ca7b47a25ba5d3ef3"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1829fd575c018327c704dad87d0c37c8ea1417bcd8ceaa09d9340f3b77e02898"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.armv7l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78667b041917c59f5062969e322e7de029fcbc47"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b71600524341f8ce6c95f15da6424c946505d7828d8d74752c1deccb0ffcba66"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.i686-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05d7a723bd15cc6406047947494be43a5b4d97e3"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "75954a68f405298b9b5b04a561e2ebf69d3bdab3ce00c5ee37350e20cc42e1bc"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.i686-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b80fe8fb1a67c308b6e01278e9e95afed6887cb2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0b0a2e7e633fe19527d7cce6980d687165aedcc125a492dd6aef5a6f97828ef6"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cd6ccf8de2471c21df569cb6679f5d151991f32"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c9b1c832ebe0a2cc29496c804617ac1b1d01de6c64f8cd0a9451c05dacb17775"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.i686-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "592fc17872228dfc5e12f98c2053938717e94e76"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "8149658ead72a28ee5e2b2c54cf4481238236ce98daa93d05c1e3d9919cb8ca7"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.i686-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b85371acc5fb54d871b17c37f2bf5109b1078572"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "12589699e5b97df76a68d8d6e061d43bfb0b39dc52b2f0dd107d3d2bda89dc7a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ccbabd8f8ed1baf7c9f7977585f174c3c729a76"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1b90e0e3861ef85556cfe875f9c342a1b87e97624b9aeb64b6f75c974ee818d4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bd78461118935fad4a4ee3103b6f936cb6017d5"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "2d836614b2da7aa4c3c24bc5af56e54b0690c66fa2f190d23b98771553e95cdf"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cf1819a9d467adbc4aa86c683f7d8c94327f4fd"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d31bd26087a1d6bd009ec73cd502f6ef9dfdd8290cf6b4746d977e326bdb2746"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26201aaa0d4bc82281d646145d2137b0af481770"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "1df03efe9e6f731fc2abb5e44f3e312f343d207a3253761fddf62c9f4f82f69c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3b5bee24ed0132189fe84b5a1cde8e6e998bbaa"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b71eb9407b183c410294d0d79f2e09d989f9eceaef0ae397c81db0f2b09d803a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7898ee5274c278faaa638d0e2ab2a3c3811cefcf"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "795c17ea4631d2be2c1c2e7cff0edd2dd517a604ae8c95477fcfee5d84dfade2"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8036ebfa4980e29d6450e4945b230a4a66559e95"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d6a2e1601bbebd159c780580a594adc82d4aef6d018a7094551777d2588dff18"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7683b1fb0a46d5d01da14213f49b4ea0cd3f66fd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c4ae70183be5ac4552f47b30cb257569d94708d9acae30d6310677b7077577d0"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2437cc8496ad3c766f03d9890ea59c66b7a68d15"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "fcb8e4ab3633fd70761f79a524a2ebe9c7a02904ab57971e47a7d1a615d9765a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea455a1156746ab51ae5dc56663ef4b60de64544"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9974b64aa1263d1f392424f51d132c49dcd5af0ae49e428836bc6064f9e33991"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7d5b684064d41bf6e547d7beafe9436d31b0d3a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "2079fba233c10a53dfa876a9f918525484da6a0a275dd107f105e23e9eae514c"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6846e2ab15e7b46ab03009d90ec100f3abf95174"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "e3d896c7e691784985f5a8867a11a6befb4384fec0289115999cb70a213d7171"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.0+0/casacorecxx.v0.2.0.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
