[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a22c7f8ccc25f82ab0062f80791f6c4aa98eb63"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d701cc118ce7d009f24c7469ef5960a9f83c72337e5458552d2353f2600174ca"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "971bf4c4d1331d4c3efbe01f71be91f53f0ad40d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "54ef68c3f9dcb4afd7a628697178e5e49c5accf8edef498dcfd25b2b1b20285d"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8050e44761c89851d90113e1c164ada370f5ede6"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "36441140fa8005cf85648c7ad29304c1b424de9e890c683da32e7b178718fd97"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a22c7f8ccc25f82ab0062f80791f6c4aa98eb63"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d701cc118ce7d009f24c7469ef5960a9f83c72337e5458552d2353f2600174ca"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b4b0e9c92128937b1f3971ac8258fcc385b9022"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "52cef004f5d1f36246b5010e272bee5d821e090637a08c2a895ec5c76e4c4484"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71997204ff679253ae1c2a1ce8c818ecf8a1048e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a92a26d4e61f90e5d49513dd79ae28bf1c4ad20b49e5f910a737ee9a0d2d28d1"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19d59c6cc89b3e103411ea23f28c6059a85a1fe2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "79e651177a10223608dc50ec87a9ae85fd4cd1af59f768fc92e2e34a8cf00185"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b4b0e9c92128937b1f3971ac8258fcc385b9022"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "52cef004f5d1f36246b5010e272bee5d821e090637a08c2a895ec5c76e4c4484"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1afe36a478a2d326c6873fa04bb67d042efa1d15"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "d680b942c4ccd6d9c741335ae35da2fff8026869e743ec1cb39a0344c5d4dc7a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94795408977b75fbed82406ca4480ea3bfe58253"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "af3d0548b9a4e37e085a9859bc221ef39116f19c958cde482b837ba37aff8fe4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv6l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d8b35fb3027866ca45f534fafa46c412286cef2"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "80133c255ddd3a9bd3019971961aedea835ff15fd52b736a36cf4929406d657e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30808faf266fe7da18b1a0651b3c74b36eb773dd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "12cba86c923d0e186524259754f495ec0aee0e05cafceb44e1395302302641f4"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv6l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4ec09216610c4793fe91ead461494624f6b9337"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a6bb05a7fac7c9fd0ee294d55add97fd85e527dc760d6caf17c9e210a92e4930"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa8fc7e8bd157f790f345abf7e96f3d02e5a9a8a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "feeb92a14b83a9196bba444bc7e49d344e691e4c844c9e3155c9ecbbc58d4ecf"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56ac93d64bb8f91d55f8ee55ec4c3a947b4ffef3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "a9617be724b164feff642bcc6845827a7b7a82ab6ea17dab247e5146a286f15e"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b621207244b0e477bec361b8a0ff04d0d020eda"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b2ce2c5f6f472cccfe5a00b77651818d2e68c97659627cc6eea05a94f16cdb35"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17426cfda7e7bdfecd4daee124c1559e655b7670"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c3006ccc0f5c801d33e2391f8baa6d8392b0679e45e2f26d58856b29e7d6bf6f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03729a7848b86e090eb18d8ea4d86f9c823c34ea"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "e6db12d8c8170ca5e09674a8db67cbc4a3d5ae4a2ceb62ef04b2af7bd86a07b6"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72a6f0322f620432dc46f86417d126c211888180"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9024089af95a6db4de94cd9b1c15f272a93e7524810e18fe394b485ca93ea348"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17426cfda7e7bdfecd4daee124c1559e655b7670"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "c3006ccc0f5c801d33e2391f8baa6d8392b0679e45e2f26d58856b29e7d6bf6f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "832c3e4f8ae606a03228d18dd9a326359ab00399"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "07b247ef55e833d75336eefacf892672975fd028ea6d467dcdafe9d271e31c8a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5b61421e3bd401477eb34e1c00bea6d680019cb"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "4c3846f1f94d65528bf70913589bb002e0f15f3c194be970ed41de724e4f7730"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e14c9aaf3fbeb7ec4ef23e6f5f4364234369759e"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "b0387358f8bd5facf32278a82823e651b069a319971292f2992a29386c0dc945"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "832c3e4f8ae606a03228d18dd9a326359ab00399"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "07b247ef55e833d75336eefacf892672975fd028ea6d467dcdafe9d271e31c8a"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aea434e99917d6c13829970ea19ca67f56a5dd15"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "fed7669a10957c89bd2a09c8617664ef4477382c293b1d4697b1545040750156"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a00cb0f41aca63101e2ec0e4a7fda6859779051"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "dde9dfcad12cd1c74d3f199e6615b7907a22ede37d4e6050d0cc7d2ebeaafd2f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3328adfe036e8384b244cacb45f0fc982d2d60ee"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "98b4d9f9d8b64abbacf80035dbb80a022cdb5945ca62e079fbdff38863c4a80f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aea434e99917d6c13829970ea19ca67f56a5dd15"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "fed7669a10957c89bd2a09c8617664ef4477382c293b1d4697b1545040750156"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f4a6e283b770389030c5fe6f4b659ed088ddd83"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "32e42d51a51e4f16152b45a755fc1d9a17e72f51ad80c139ae7c97bc39256730"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e3589f003ab3e7c9b408228179d8dce0ad9f043"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0037265d29f8535e67aed5ee67ac5f09369fdd9a4e5911d951e129f8bde076e1"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2b21e0a06d4bcb32b856fbf775fd80fc96933ed"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "eb75b37f5f5208672b530692c72db7b1a8ebacba9273b082b0e50e3ab5e95327"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f4a6e283b770389030c5fe6f4b659ed088ddd83"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "32e42d51a51e4f16152b45a755fc1d9a17e72f51ad80c139ae7c97bc39256730"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5514ad8b8f02f68ad74bd9876ce69f1227a4477b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9eb838ebc6d1cc66e7ad223d71664daab5e15add5046d670bb9561f5e72cfc1f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a920bc1c5be5705679c4221e52a971a45c18da91"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0a9c66f5dafbc83dd0b7df7be6276e8a4200c09191dfaccf8918d1c9d6ccfe32"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "925054a94630127d11cdead3c14b0e12b24b51ee"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "0ba177a083dbc2edb615df006d2abdaf2613e257c0833930341d4a80eca5de26"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5514ad8b8f02f68ad74bd9876ce69f1227a4477b"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "9eb838ebc6d1cc66e7ad223d71664daab5e15add5046d670bb9561f5e72cfc1f"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fb9fc58d9c581898ac88ad004b53dd41eaf495c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "572685a41875e0bf3eca0c09fc10f7d468e4f5a7af76d00e9799e0ec901486fe"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24ad964b35cc87c1a198d98f243381179e38915a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "294aade102ed21ee7a183c31510667e5f3a8a27a029a7ce3823cae73c99cf7ca"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3306df4f950c7b63560d8ad973c0f0f607b1e784"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "60c8e1fa39e3656344e84d28d2485e62d42169f32187a59800f4bef83ff8f572"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[casacorecxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fb9fc58d9c581898ac88ad004b53dd41eaf495c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[casacorecxx.download]]
    sha256 = "572685a41875e0bf3eca0c09fc10f7d468e4f5a7af76d00e9799e0ec901486fe"
    url = "https://github.com/JuliaBinaryWrappers/casacorecxx_jll.jl/releases/download/casacorecxx-v0.2.1+1/casacorecxx.v0.2.1.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
